package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article_category_keyword
 *
 * @mbg.generated do_not_delete_during_merge Thu Jul 12 17:09:12 CST 2018
 */
public class ArticleCategoryKeyword {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category_keyword.article_category_keyword_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer articleCategoryKeywordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category_keyword.article_category_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer articleCategoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category_keyword.article_keyword_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer articleKeywordId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category_keyword.article_category_keyword_id
	 * @return  the value of article_category_keyword.article_category_keyword_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getArticleCategoryKeywordId() {
		return articleCategoryKeywordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category_keyword.article_category_keyword_id
	 * @param articleCategoryKeywordId  the value for article_category_keyword.article_category_keyword_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setArticleCategoryKeywordId(Integer articleCategoryKeywordId) {
		this.articleCategoryKeywordId = articleCategoryKeywordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category_keyword.article_category_id
	 * @return  the value of article_category_keyword.article_category_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getArticleCategoryId() {
		return articleCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category_keyword.article_category_id
	 * @param articleCategoryId  the value for article_category_keyword.article_category_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setArticleCategoryId(Integer articleCategoryId) {
		this.articleCategoryId = articleCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category_keyword.article_keyword_id
	 * @return  the value of article_category_keyword.article_keyword_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getArticleKeywordId() {
		return articleKeywordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category_keyword.article_keyword_id
	 * @param articleKeywordId  the value for article_category_keyword.article_keyword_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setArticleKeywordId(Integer articleKeywordId) {
		this.articleKeywordId = articleKeywordId;
	}
}