package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article_category
 *
 * @mbg.generated do_not_delete_during_merge Thu Jul 12 17:09:12 CST 2018
 */
public class ArticleCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category.article_category_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer articleCategoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category.article_category_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String articleCategoryName;
	/**
	 * Database Column Remarks: 0 ∆Ù”√ 1 ≤ª∆Ù”√ This field was generated by MyBatis Generator. This field corresponds to the database column article_category.article_category_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer articleCategoryStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category.article_category_id
	 * @return  the value of article_category.article_category_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getArticleCategoryId() {
		return articleCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category.article_category_id
	 * @param articleCategoryId  the value for article_category.article_category_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setArticleCategoryId(Integer articleCategoryId) {
		this.articleCategoryId = articleCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category.article_category_name
	 * @return  the value of article_category.article_category_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getArticleCategoryName() {
		return articleCategoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category.article_category_name
	 * @param articleCategoryName  the value for article_category.article_category_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setArticleCategoryName(String articleCategoryName) {
		this.articleCategoryName = articleCategoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category.article_category_status
	 * @return  the value of article_category.article_category_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getArticleCategoryStatus() {
		return articleCategoryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category.article_category_status
	 * @param articleCategoryStatus  the value for article_category.article_category_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setArticleCategoryStatus(Integer articleCategoryStatus) {
		this.articleCategoryStatus = articleCategoryStatus;
	}
}