package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table clarksons_table
 */
public class ClarksonsTable {

	/**
	 * Database Column Remarks: ID This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.clarksons_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer clarksonsTableId;
	/**
	 * Database Column Remarks: 表名 This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.clarksons_table_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String clarksonsTableName;
	/**
	 * Database Column Remarks: URL This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.clarksons_table_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String clarksonsTableUrl;
	/**
	 * Database Column Remarks: 分类 This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.clarksons_table_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String clarksonsTableCategory;
	/**
	 * Database Column Remarks: 数据库英文名 This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.clarksons_table_database_en
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String clarksonsTableDatabaseEn;
	/**
	 * Database Column Remarks: 数据库中文名 This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.clarksons_table_database_ch
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String clarksonsTableDatabaseCh;
	/**
	 * Database Column Remarks: 下载使能标志 This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.download_enabled
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer downloadEnabled;
	/**
	 * Database Column Remarks: 下载状态，0: 正常 1:不能下载 This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.download_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer downloadStatus;
	/**
	 * Database Column Remarks: 下载数据间隔时间，单位天 This field was generated by MyBatis Generator. This field corresponds to the database column clarksons_table.download_schedule_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer downloadScheduleInterval;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.clarksons_table_id
	 * @return  the value of clarksons_table.clarksons_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getClarksonsTableId() {
		return clarksonsTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.clarksons_table_id
	 * @param clarksonsTableId  the value for clarksons_table.clarksons_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setClarksonsTableId(Integer clarksonsTableId) {
		this.clarksonsTableId = clarksonsTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.clarksons_table_name
	 * @return  the value of clarksons_table.clarksons_table_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getClarksonsTableName() {
		return clarksonsTableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.clarksons_table_name
	 * @param clarksonsTableName  the value for clarksons_table.clarksons_table_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setClarksonsTableName(String clarksonsTableName) {
		this.clarksonsTableName = clarksonsTableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.clarksons_table_url
	 * @return  the value of clarksons_table.clarksons_table_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getClarksonsTableUrl() {
		return clarksonsTableUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.clarksons_table_url
	 * @param clarksonsTableUrl  the value for clarksons_table.clarksons_table_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setClarksonsTableUrl(String clarksonsTableUrl) {
		this.clarksonsTableUrl = clarksonsTableUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.clarksons_table_category
	 * @return  the value of clarksons_table.clarksons_table_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getClarksonsTableCategory() {
		return clarksonsTableCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.clarksons_table_category
	 * @param clarksonsTableCategory  the value for clarksons_table.clarksons_table_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setClarksonsTableCategory(String clarksonsTableCategory) {
		this.clarksonsTableCategory = clarksonsTableCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.clarksons_table_database_en
	 * @return  the value of clarksons_table.clarksons_table_database_en
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getClarksonsTableDatabaseEn() {
		return clarksonsTableDatabaseEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.clarksons_table_database_en
	 * @param clarksonsTableDatabaseEn  the value for clarksons_table.clarksons_table_database_en
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setClarksonsTableDatabaseEn(String clarksonsTableDatabaseEn) {
		this.clarksonsTableDatabaseEn = clarksonsTableDatabaseEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.clarksons_table_database_ch
	 * @return  the value of clarksons_table.clarksons_table_database_ch
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getClarksonsTableDatabaseCh() {
		return clarksonsTableDatabaseCh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.clarksons_table_database_ch
	 * @param clarksonsTableDatabaseCh  the value for clarksons_table.clarksons_table_database_ch
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setClarksonsTableDatabaseCh(String clarksonsTableDatabaseCh) {
		this.clarksonsTableDatabaseCh = clarksonsTableDatabaseCh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.download_enabled
	 * @return  the value of clarksons_table.download_enabled
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getDownloadEnabled() {
		return downloadEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.download_enabled
	 * @param downloadEnabled  the value for clarksons_table.download_enabled
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setDownloadEnabled(Integer downloadEnabled) {
		this.downloadEnabled = downloadEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.download_status
	 * @return  the value of clarksons_table.download_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getDownloadStatus() {
		return downloadStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.download_status
	 * @param downloadStatus  the value for clarksons_table.download_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setDownloadStatus(Integer downloadStatus) {
		this.downloadStatus = downloadStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clarksons_table.download_schedule_interval
	 * @return  the value of clarksons_table.download_schedule_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getDownloadScheduleInterval() {
		return downloadScheduleInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clarksons_table.download_schedule_interval
	 * @param downloadScheduleInterval  the value for clarksons_table.download_schedule_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setDownloadScheduleInterval(Integer downloadScheduleInterval) {
		this.downloadScheduleInterval = downloadScheduleInterval;
	}
}