package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crsl_session
 */
public class CrslSessionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crsl_session.crsl_session_id
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    private Integer crslSessionId;

    /**
     * Database Column Remarks:
     *   loginname, logic pk
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crsl_session.crsl_session_login_name
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    private String crslSessionLoginName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crsl_session.crsl_session_id
     *
     * @return the value of crsl_session.crsl_session_id
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public Integer getCrslSessionId() {
        return crslSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crsl_session.crsl_session_id
     *
     * @param crslSessionId the value for crsl_session.crsl_session_id
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void setCrslSessionId(Integer crslSessionId) {
        this.crslSessionId = crslSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crsl_session.crsl_session_login_name
     *
     * @return the value of crsl_session.crsl_session_login_name
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public String getCrslSessionLoginName() {
        return crslSessionLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crsl_session.crsl_session_login_name
     *
     * @param crslSessionLoginName the value for crsl_session.crsl_session_login_name
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void setCrslSessionLoginName(String crslSessionLoginName) {
        this.crslSessionLoginName = crslSessionLoginName;
    }
}