package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crsl_table
 */
public class CrslTable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE.crsl_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE.crsl_table_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslTableName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE.crsl_database_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslDatabaseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE.crsl_table_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslTableCategory;
	/**
	 * Database Column Remarks: 1 ²»Õý³£×´Ì¬ This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE.crsl_table_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE.crsl_table_uri
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslTableUri;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE.crsl_table_id
	 * @return  the value of CRSL_TABLE.crsl_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableId() {
		return crslTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE.crsl_table_id
	 * @param crslTableId  the value for CRSL_TABLE.crsl_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableId(Integer crslTableId) {
		this.crslTableId = crslTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE.crsl_table_name
	 * @return  the value of CRSL_TABLE.crsl_table_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslTableName() {
		return crslTableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE.crsl_table_name
	 * @param crslTableName  the value for CRSL_TABLE.crsl_table_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableName(String crslTableName) {
		this.crslTableName = crslTableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE.crsl_database_id
	 * @return  the value of CRSL_TABLE.crsl_database_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslDatabaseId() {
		return crslDatabaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE.crsl_database_id
	 * @param crslDatabaseId  the value for CRSL_TABLE.crsl_database_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslDatabaseId(Integer crslDatabaseId) {
		this.crslDatabaseId = crslDatabaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE.crsl_table_category
	 * @return  the value of CRSL_TABLE.crsl_table_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslTableCategory() {
		return crslTableCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE.crsl_table_category
	 * @param crslTableCategory  the value for CRSL_TABLE.crsl_table_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableCategory(String crslTableCategory) {
		this.crslTableCategory = crslTableCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE.crsl_table_status
	 * @return  the value of CRSL_TABLE.crsl_table_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableStatus() {
		return crslTableStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE.crsl_table_status
	 * @param crslTableStatus  the value for CRSL_TABLE.crsl_table_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableStatus(Integer crslTableStatus) {
		this.crslTableStatus = crslTableStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE.crsl_table_uri
	 * @return  the value of CRSL_TABLE.crsl_table_uri
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslTableUri() {
		return crslTableUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE.crsl_table_uri
	 * @param crslTableUri  the value for CRSL_TABLE.crsl_table_uri
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableUri(String crslTableUri) {
		this.crslTableUri = crslTableUri;
	}
}