package com.csicerc.dss.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrslTableDownSchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public CrslTableDownSchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCrslTableDownSchIdIsNull() {
            addCriterion("crsl_table_down_sch_id is null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdIsNotNull() {
            addCriterion("crsl_table_down_sch_id is not null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_id =", value, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdNotEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_id <>", value, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdGreaterThan(Integer value) {
            addCriterion("crsl_table_down_sch_id >", value, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_id >=", value, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdLessThan(Integer value) {
            addCriterion("crsl_table_down_sch_id <", value, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdLessThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_id <=", value, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdIn(List<Integer> values) {
            addCriterion("crsl_table_down_sch_id in", values, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdNotIn(List<Integer> values) {
            addCriterion("crsl_table_down_sch_id not in", values, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_sch_id between", value1, value2, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIdNotBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_sch_id not between", value1, value2, "crslTableDownSchId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeIsNull() {
            addCriterion("crsl_table_down_sch_time is null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeIsNotNull() {
            addCriterion("crsl_table_down_sch_time is not null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeEqualTo(Date value) {
            addCriterion("crsl_table_down_sch_time =", value, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeNotEqualTo(Date value) {
            addCriterion("crsl_table_down_sch_time <>", value, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeGreaterThan(Date value) {
            addCriterion("crsl_table_down_sch_time >", value, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("crsl_table_down_sch_time >=", value, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeLessThan(Date value) {
            addCriterion("crsl_table_down_sch_time <", value, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeLessThanOrEqualTo(Date value) {
            addCriterion("crsl_table_down_sch_time <=", value, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeIn(List<Date> values) {
            addCriterion("crsl_table_down_sch_time in", values, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeNotIn(List<Date> values) {
            addCriterion("crsl_table_down_sch_time not in", values, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeBetween(Date value1, Date value2) {
            addCriterion("crsl_table_down_sch_time between", value1, value2, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchTimeNotBetween(Date value1, Date value2) {
            addCriterion("crsl_table_down_sch_time not between", value1, value2, "crslTableDownSchTime");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalIsNull() {
            addCriterion("crsl_table_down_sch_interval is null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalIsNotNull() {
            addCriterion("crsl_table_down_sch_interval is not null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_interval =", value, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalNotEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_interval <>", value, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalGreaterThan(Integer value) {
            addCriterion("crsl_table_down_sch_interval >", value, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_interval >=", value, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalLessThan(Integer value) {
            addCriterion("crsl_table_down_sch_interval <", value, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalLessThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_interval <=", value, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalIn(List<Integer> values) {
            addCriterion("crsl_table_down_sch_interval in", values, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalNotIn(List<Integer> values) {
            addCriterion("crsl_table_down_sch_interval not in", values, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_sch_interval between", value1, value2, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchIntervalNotBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_sch_interval not between", value1, value2, "crslTableDownSchInterval");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusIsNull() {
            addCriterion("crsl_table_down_sch_status is null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusIsNotNull() {
            addCriterion("crsl_table_down_sch_status is not null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_status =", value, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusNotEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_status <>", value, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusGreaterThan(Integer value) {
            addCriterion("crsl_table_down_sch_status >", value, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_status >=", value, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusLessThan(Integer value) {
            addCriterion("crsl_table_down_sch_status <", value, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusLessThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_status <=", value, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusIn(List<Integer> values) {
            addCriterion("crsl_table_down_sch_status in", values, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusNotIn(List<Integer> values) {
            addCriterion("crsl_table_down_sch_status not in", values, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_sch_status between", value1, value2, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_sch_status not between", value1, value2, "crslTableDownSchStatus");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerIsNull() {
            addCriterion("crsl_table_down_sch_owner is null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerIsNotNull() {
            addCriterion("crsl_table_down_sch_owner is not null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_owner =", value, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerNotEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_owner <>", value, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerGreaterThan(Integer value) {
            addCriterion("crsl_table_down_sch_owner >", value, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerGreaterThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_owner >=", value, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerLessThan(Integer value) {
            addCriterion("crsl_table_down_sch_owner <", value, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerLessThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_sch_owner <=", value, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerIn(List<Integer> values) {
            addCriterion("crsl_table_down_sch_owner in", values, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerNotIn(List<Integer> values) {
            addCriterion("crsl_table_down_sch_owner not in", values, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_sch_owner between", value1, value2, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownSchOwnerNotBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_sch_owner not between", value1, value2, "crslTableDownSchOwner");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameIsNull() {
            addCriterion("qrtz_trigger_name is null");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameIsNotNull() {
            addCriterion("qrtz_trigger_name is not null");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameEqualTo(String value) {
            addCriterion("qrtz_trigger_name =", value, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameNotEqualTo(String value) {
            addCriterion("qrtz_trigger_name <>", value, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameGreaterThan(String value) {
            addCriterion("qrtz_trigger_name >", value, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameGreaterThanOrEqualTo(String value) {
            addCriterion("qrtz_trigger_name >=", value, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameLessThan(String value) {
            addCriterion("qrtz_trigger_name <", value, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameLessThanOrEqualTo(String value) {
            addCriterion("qrtz_trigger_name <=", value, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameLike(String value) {
            addCriterion("qrtz_trigger_name like", value, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameNotLike(String value) {
            addCriterion("qrtz_trigger_name not like", value, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameIn(List<String> values) {
            addCriterion("qrtz_trigger_name in", values, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameNotIn(List<String> values) {
            addCriterion("qrtz_trigger_name not in", values, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameBetween(String value1, String value2) {
            addCriterion("qrtz_trigger_name between", value1, value2, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andQrtzTriggerNameNotBetween(String value1, String value2) {
            addCriterion("qrtz_trigger_name not between", value1, value2, "qrtzTriggerName");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdIsNull() {
            addCriterion("crsl_table_down_table_id is null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdIsNotNull() {
            addCriterion("crsl_table_down_table_id is not null");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdEqualTo(Integer value) {
            addCriterion("crsl_table_down_table_id =", value, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdNotEqualTo(Integer value) {
            addCriterion("crsl_table_down_table_id <>", value, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdGreaterThan(Integer value) {
            addCriterion("crsl_table_down_table_id >", value, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_table_id >=", value, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdLessThan(Integer value) {
            addCriterion("crsl_table_down_table_id <", value, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdLessThanOrEqualTo(Integer value) {
            addCriterion("crsl_table_down_table_id <=", value, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdIn(List<Integer> values) {
            addCriterion("crsl_table_down_table_id in", values, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdNotIn(List<Integer> values) {
            addCriterion("crsl_table_down_table_id not in", values, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_table_id between", value1, value2, "crslTableDownTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableDownTableIdNotBetween(Integer value1, Integer value2) {
            addCriterion("crsl_table_down_table_id not between", value1, value2, "crslTableDownTableId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 19 10:33:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crsl_table_down_sch
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}