package com.csicerc.dss.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crsl_table_down_sch
 */
public class CrslTableDownSch {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_sch.crsl_table_down_sch_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownSchId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_sch.crsl_table_down_sch_time
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Date crslTableDownSchTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_sch.crsl_table_down_sch_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownSchInterval;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_sch.crsl_table_down_sch_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownSchStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_sch.crsl_table_down_sch_owner
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownSchOwner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_sch.qrtz_trigger_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String qrtzTriggerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_sch.crsl_table_down_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownTableId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_sch.crsl_table_down_sch_id
	 * @return  the value of crsl_table_down_sch.crsl_table_down_sch_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownSchId() {
		return crslTableDownSchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_sch.crsl_table_down_sch_id
	 * @param crslTableDownSchId  the value for crsl_table_down_sch.crsl_table_down_sch_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownSchId(Integer crslTableDownSchId) {
		this.crslTableDownSchId = crslTableDownSchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_sch.crsl_table_down_sch_time
	 * @return  the value of crsl_table_down_sch.crsl_table_down_sch_time
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Date getCrslTableDownSchTime() {
		return crslTableDownSchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_sch.crsl_table_down_sch_time
	 * @param crslTableDownSchTime  the value for crsl_table_down_sch.crsl_table_down_sch_time
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownSchTime(Date crslTableDownSchTime) {
		this.crslTableDownSchTime = crslTableDownSchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_sch.crsl_table_down_sch_interval
	 * @return  the value of crsl_table_down_sch.crsl_table_down_sch_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownSchInterval() {
		return crslTableDownSchInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_sch.crsl_table_down_sch_interval
	 * @param crslTableDownSchInterval  the value for crsl_table_down_sch.crsl_table_down_sch_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownSchInterval(Integer crslTableDownSchInterval) {
		this.crslTableDownSchInterval = crslTableDownSchInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_sch.crsl_table_down_sch_status
	 * @return  the value of crsl_table_down_sch.crsl_table_down_sch_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownSchStatus() {
		return crslTableDownSchStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_sch.crsl_table_down_sch_status
	 * @param crslTableDownSchStatus  the value for crsl_table_down_sch.crsl_table_down_sch_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownSchStatus(Integer crslTableDownSchStatus) {
		this.crslTableDownSchStatus = crslTableDownSchStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_sch.crsl_table_down_sch_owner
	 * @return  the value of crsl_table_down_sch.crsl_table_down_sch_owner
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownSchOwner() {
		return crslTableDownSchOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_sch.crsl_table_down_sch_owner
	 * @param crslTableDownSchOwner  the value for crsl_table_down_sch.crsl_table_down_sch_owner
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownSchOwner(Integer crslTableDownSchOwner) {
		this.crslTableDownSchOwner = crslTableDownSchOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_sch.qrtz_trigger_name
	 * @return  the value of crsl_table_down_sch.qrtz_trigger_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getQrtzTriggerName() {
		return qrtzTriggerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_sch.qrtz_trigger_name
	 * @param qrtzTriggerName  the value for crsl_table_down_sch.qrtz_trigger_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setQrtzTriggerName(String qrtzTriggerName) {
		this.qrtzTriggerName = qrtzTriggerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_sch.crsl_table_down_table_id
	 * @return  the value of crsl_table_down_sch.crsl_table_down_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownTableId() {
		return crslTableDownTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_sch.crsl_table_down_table_id
	 * @param crslTableDownTableId  the value for crsl_table_down_sch.crsl_table_down_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownTableId(Integer crslTableDownTableId) {
		this.crslTableDownTableId = crslTableDownTableId;
	}
}