package com.csicerc.dss.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crsl_table_down_rec
 */
public class CrslTableDownRec {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_rec.crsl_table_down_rec_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownRecId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_rec.crsl_table_down_start
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Date crslTableDownStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_rec.crsl_table_down_end
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Date crslTableDownEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_rec.crsl_table_down_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownTableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_rec.crsl_table_down_rec_qty
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownRecQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_rec.crsl_table_down_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crsl_table_down_rec.crsl_table_down_sch_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableDownSchId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_rec.crsl_table_down_rec_id
	 * @return  the value of crsl_table_down_rec.crsl_table_down_rec_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownRecId() {
		return crslTableDownRecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_rec.crsl_table_down_rec_id
	 * @param crslTableDownRecId  the value for crsl_table_down_rec.crsl_table_down_rec_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownRecId(Integer crslTableDownRecId) {
		this.crslTableDownRecId = crslTableDownRecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_rec.crsl_table_down_start
	 * @return  the value of crsl_table_down_rec.crsl_table_down_start
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Date getCrslTableDownStart() {
		return crslTableDownStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_rec.crsl_table_down_start
	 * @param crslTableDownStart  the value for crsl_table_down_rec.crsl_table_down_start
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownStart(Date crslTableDownStart) {
		this.crslTableDownStart = crslTableDownStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_rec.crsl_table_down_end
	 * @return  the value of crsl_table_down_rec.crsl_table_down_end
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Date getCrslTableDownEnd() {
		return crslTableDownEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_rec.crsl_table_down_end
	 * @param crslTableDownEnd  the value for crsl_table_down_rec.crsl_table_down_end
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownEnd(Date crslTableDownEnd) {
		this.crslTableDownEnd = crslTableDownEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_rec.crsl_table_down_table_id
	 * @return  the value of crsl_table_down_rec.crsl_table_down_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownTableId() {
		return crslTableDownTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_rec.crsl_table_down_table_id
	 * @param crslTableDownTableId  the value for crsl_table_down_rec.crsl_table_down_table_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownTableId(Integer crslTableDownTableId) {
		this.crslTableDownTableId = crslTableDownTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_rec.crsl_table_down_rec_qty
	 * @return  the value of crsl_table_down_rec.crsl_table_down_rec_qty
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownRecQty() {
		return crslTableDownRecQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_rec.crsl_table_down_rec_qty
	 * @param crslTableDownRecQty  the value for crsl_table_down_rec.crsl_table_down_rec_qty
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownRecQty(Integer crslTableDownRecQty) {
		this.crslTableDownRecQty = crslTableDownRecQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_rec.crsl_table_down_status
	 * @return  the value of crsl_table_down_rec.crsl_table_down_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownStatus() {
		return crslTableDownStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_rec.crsl_table_down_status
	 * @param crslTableDownStatus  the value for crsl_table_down_rec.crsl_table_down_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownStatus(Integer crslTableDownStatus) {
		this.crslTableDownStatus = crslTableDownStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crsl_table_down_rec.crsl_table_down_sch_id
	 * @return  the value of crsl_table_down_rec.crsl_table_down_sch_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableDownSchId() {
		return crslTableDownSchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crsl_table_down_rec.crsl_table_down_sch_id
	 * @param crslTableDownSchId  the value for crsl_table_down_rec.crsl_table_down_sch_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableDownSchId(Integer crslTableDownSchId) {
		this.crslTableDownSchId = crslTableDownSchId;
	}
}