package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table CRSL_TABLE_FIELD
 */
public class CrslTableField {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE_FIELD.CRSL_TABLE_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableFieldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE_FIELD.CRSL_TABLE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_TABLE_FIELD.CRSL_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslFieldId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE_FIELD.CRSL_TABLE_FIELD_ID
	 * @return  the value of CRSL_TABLE_FIELD.CRSL_TABLE_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableFieldId() {
		return crslTableFieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE_FIELD.CRSL_TABLE_FIELD_ID
	 * @param crslTableFieldId  the value for CRSL_TABLE_FIELD.CRSL_TABLE_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableFieldId(Integer crslTableFieldId) {
		this.crslTableFieldId = crslTableFieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE_FIELD.CRSL_TABLE_ID
	 * @return  the value of CRSL_TABLE_FIELD.CRSL_TABLE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableId() {
		return crslTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE_FIELD.CRSL_TABLE_ID
	 * @param crslTableId  the value for CRSL_TABLE_FIELD.CRSL_TABLE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableId(Integer crslTableId) {
		this.crslTableId = crslTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_TABLE_FIELD.CRSL_FIELD_ID
	 * @return  the value of CRSL_TABLE_FIELD.CRSL_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslFieldId() {
		return crslFieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_TABLE_FIELD.CRSL_FIELD_ID
	 * @param crslFieldId  the value for CRSL_TABLE_FIELD.CRSL_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldId(Integer crslFieldId) {
		this.crslFieldId = crslFieldId;
	}
}