package com.csicerc.dss.domain;

import java.util.ArrayList;
import java.util.List;

public class CrslFieldsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public CrslFieldsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCrslFieldIdIsNull() {
            addCriterion("CRSL_FIELD_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdIsNotNull() {
            addCriterion("CRSL_FIELD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdEqualTo(Integer value) {
            addCriterion("CRSL_FIELD_ID =", value, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdNotEqualTo(Integer value) {
            addCriterion("CRSL_FIELD_ID <>", value, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdGreaterThan(Integer value) {
            addCriterion("CRSL_FIELD_ID >", value, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CRSL_FIELD_ID >=", value, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdLessThan(Integer value) {
            addCriterion("CRSL_FIELD_ID <", value, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdLessThanOrEqualTo(Integer value) {
            addCriterion("CRSL_FIELD_ID <=", value, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdIn(List<Integer> values) {
            addCriterion("CRSL_FIELD_ID in", values, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdNotIn(List<Integer> values) {
            addCriterion("CRSL_FIELD_ID not in", values, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdBetween(Integer value1, Integer value2) {
            addCriterion("CRSL_FIELD_ID between", value1, value2, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CRSL_FIELD_ID not between", value1, value2, "crslFieldId");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameIsNull() {
            addCriterion("CRSL_FIELD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameIsNotNull() {
            addCriterion("CRSL_FIELD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameEqualTo(String value) {
            addCriterion("CRSL_FIELD_NAME =", value, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameNotEqualTo(String value) {
            addCriterion("CRSL_FIELD_NAME <>", value, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameGreaterThan(String value) {
            addCriterion("CRSL_FIELD_NAME >", value, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameGreaterThanOrEqualTo(String value) {
            addCriterion("CRSL_FIELD_NAME >=", value, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameLessThan(String value) {
            addCriterion("CRSL_FIELD_NAME <", value, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameLessThanOrEqualTo(String value) {
            addCriterion("CRSL_FIELD_NAME <=", value, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameLike(String value) {
            addCriterion("CRSL_FIELD_NAME like", value, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameNotLike(String value) {
            addCriterion("CRSL_FIELD_NAME not like", value, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameIn(List<String> values) {
            addCriterion("CRSL_FIELD_NAME in", values, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameNotIn(List<String> values) {
            addCriterion("CRSL_FIELD_NAME not in", values, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameBetween(String value1, String value2) {
            addCriterion("CRSL_FIELD_NAME between", value1, value2, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldNameNotBetween(String value1, String value2) {
            addCriterion("CRSL_FIELD_NAME not between", value1, value2, "crslFieldName");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledIsNull() {
            addCriterion("CRSL_FIELD_DISABLED is null");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledIsNotNull() {
            addCriterion("CRSL_FIELD_DISABLED is not null");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledEqualTo(Boolean value) {
            addCriterion("CRSL_FIELD_DISABLED =", value, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledNotEqualTo(Boolean value) {
            addCriterion("CRSL_FIELD_DISABLED <>", value, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledGreaterThan(Boolean value) {
            addCriterion("CRSL_FIELD_DISABLED >", value, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("CRSL_FIELD_DISABLED >=", value, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledLessThan(Boolean value) {
            addCriterion("CRSL_FIELD_DISABLED <", value, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledLessThanOrEqualTo(Boolean value) {
            addCriterion("CRSL_FIELD_DISABLED <=", value, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledIn(List<Boolean> values) {
            addCriterion("CRSL_FIELD_DISABLED in", values, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledNotIn(List<Boolean> values) {
            addCriterion("CRSL_FIELD_DISABLED not in", values, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledBetween(Boolean value1, Boolean value2) {
            addCriterion("CRSL_FIELD_DISABLED between", value1, value2, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslFieldDisabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("CRSL_FIELD_DISABLED not between", value1, value2, "crslFieldDisabled");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdIsNull() {
            addCriterion("CRSL_DATABASE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdIsNotNull() {
            addCriterion("CRSL_DATABASE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdEqualTo(Integer value) {
            addCriterion("CRSL_DATABASE_ID =", value, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdNotEqualTo(Integer value) {
            addCriterion("CRSL_DATABASE_ID <>", value, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdGreaterThan(Integer value) {
            addCriterion("CRSL_DATABASE_ID >", value, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CRSL_DATABASE_ID >=", value, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdLessThan(Integer value) {
            addCriterion("CRSL_DATABASE_ID <", value, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdLessThanOrEqualTo(Integer value) {
            addCriterion("CRSL_DATABASE_ID <=", value, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdIn(List<Integer> values) {
            addCriterion("CRSL_DATABASE_ID in", values, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdNotIn(List<Integer> values) {
            addCriterion("CRSL_DATABASE_ID not in", values, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdBetween(Integer value1, Integer value2) {
            addCriterion("CRSL_DATABASE_ID between", value1, value2, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslDatabaseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CRSL_DATABASE_ID not between", value1, value2, "crslDatabaseId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdIsNull() {
            addCriterion("CRSL_TABLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdIsNotNull() {
            addCriterion("CRSL_TABLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdEqualTo(Integer value) {
            addCriterion("CRSL_TABLE_ID =", value, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdNotEqualTo(Integer value) {
            addCriterion("CRSL_TABLE_ID <>", value, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdGreaterThan(Integer value) {
            addCriterion("CRSL_TABLE_ID >", value, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CRSL_TABLE_ID >=", value, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdLessThan(Integer value) {
            addCriterion("CRSL_TABLE_ID <", value, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdLessThanOrEqualTo(Integer value) {
            addCriterion("CRSL_TABLE_ID <=", value, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdIn(List<Integer> values) {
            addCriterion("CRSL_TABLE_ID in", values, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdNotIn(List<Integer> values) {
            addCriterion("CRSL_TABLE_ID not in", values, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdBetween(Integer value1, Integer value2) {
            addCriterion("CRSL_TABLE_ID between", value1, value2, "crslTableId");
            return (Criteria) this;
        }

        public Criteria andCrslTableIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CRSL_TABLE_ID not between", value1, value2, "crslTableId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crsl_fields
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 19 10:33:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crsl_fields
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}