package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table CRSL_FIELD_TYPE
 */
public class CrslFieldType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslFieldTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_FORMAT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldTypeFormat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_ID
	 * @return  the value of CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslFieldTypeId() {
		return crslFieldTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_ID
	 * @param crslFieldTypeId  the value for CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldTypeId(Integer crslFieldTypeId) {
		this.crslFieldTypeId = crslFieldTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_NAME
	 * @return  the value of CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldTypeName() {
		return crslFieldTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_NAME
	 * @param crslFieldTypeName  the value for CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldTypeName(String crslFieldTypeName) {
		this.crslFieldTypeName = crslFieldTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_FORMAT
	 * @return  the value of CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_FORMAT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldTypeFormat() {
		return crslFieldTypeFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_FORMAT
	 * @param crslFieldTypeFormat  the value for CRSL_FIELD_TYPE.CRSL_FIELD_TYPE_FORMAT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldTypeFormat(String crslFieldTypeFormat) {
		this.crslFieldTypeFormat = crslFieldTypeFormat;
	}
}