package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crsl_database
 */
public class CrslDatabase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_DATABASE.crsl_database_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslDatabaseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_DATABASE.crsl_database_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslDatabaseName;
	/**
	 * Database Column Remarks: session访问的数据库 This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_DATABASE.crsl_session_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslSessionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_DATABASE.crsl_database_name_cn
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslDatabaseNameCn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_DATABASE.crsl_database_id
	 * @return  the value of CRSL_DATABASE.crsl_database_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslDatabaseId() {
		return crslDatabaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_DATABASE.crsl_database_id
	 * @param crslDatabaseId  the value for CRSL_DATABASE.crsl_database_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslDatabaseId(Integer crslDatabaseId) {
		this.crslDatabaseId = crslDatabaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_DATABASE.crsl_database_name
	 * @return  the value of CRSL_DATABASE.crsl_database_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslDatabaseName() {
		return crslDatabaseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_DATABASE.crsl_database_name
	 * @param crslDatabaseName  the value for CRSL_DATABASE.crsl_database_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslDatabaseName(String crslDatabaseName) {
		this.crslDatabaseName = crslDatabaseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_DATABASE.crsl_session_id
	 * @return  the value of CRSL_DATABASE.crsl_session_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslSessionId() {
		return crslSessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_DATABASE.crsl_session_id
	 * @param crslSessionId  the value for CRSL_DATABASE.crsl_session_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslSessionId(Integer crslSessionId) {
		this.crslSessionId = crslSessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_DATABASE.crsl_database_name_cn
	 * @return  the value of CRSL_DATABASE.crsl_database_name_cn
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslDatabaseNameCn() {
		return crslDatabaseNameCn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_DATABASE.crsl_database_name_cn
	 * @param crslDatabaseNameCn  the value for CRSL_DATABASE.crsl_database_name_cn
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslDatabaseNameCn(String crslDatabaseNameCn) {
		this.crslDatabaseNameCn = crslDatabaseNameCn;
	}
}