package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table CRSL_FIELD
 */
public class CrslField {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslFieldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_DISABLED
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Boolean crslFieldDisabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_DATABASE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslDatabaseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_TABLE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslTableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_TEMPLATE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldTemplate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_DATAFORMATSTRING
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldDataformatstring;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_DATAFIELDTYPE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslFieldDatafieldtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_DISPLAYNAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldDisplayname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_SORTABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Boolean crslFieldSortable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_TITLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_HASHISTORYAVAILABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Boolean crslFieldHashistoryavailable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_SORTORDER
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer crslFieldSortorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldAttributesCrslField;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_NG_CLICK
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldAttributesNgClick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_STYLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldAttributesStyle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CLASS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldAttributesClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_INGRID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Boolean crslFieldAttributesCrslIngrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldHeaderAttributesCrslField;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_NG_CLICK
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldHeaderAttributesNgClick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_STYLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldHeaderAttributesStyle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CLASS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String crslFieldHeaderAttributesClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_INGRID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Boolean crslFieldHeaderAttributesCrslIngrid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_ID
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslFieldId() {
		return crslFieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_ID
	 * @param crslFieldId  the value for CRSL_FIELD.CRSL_FIELD_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldId(Integer crslFieldId) {
		this.crslFieldId = crslFieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_NAME
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldName() {
		return crslFieldName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_NAME
	 * @param crslFieldName  the value for CRSL_FIELD.CRSL_FIELD_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldName(String crslFieldName) {
		this.crslFieldName = crslFieldName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_DISABLED
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_DISABLED
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Boolean getCrslFieldDisabled() {
		return crslFieldDisabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_DISABLED
	 * @param crslFieldDisabled  the value for CRSL_FIELD.CRSL_FIELD_DISABLED
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldDisabled(Boolean crslFieldDisabled) {
		this.crslFieldDisabled = crslFieldDisabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_DATABASE_ID
	 * @return  the value of CRSL_FIELD.CRSL_DATABASE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslDatabaseId() {
		return crslDatabaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_DATABASE_ID
	 * @param crslDatabaseId  the value for CRSL_FIELD.CRSL_DATABASE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslDatabaseId(Integer crslDatabaseId) {
		this.crslDatabaseId = crslDatabaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_TABLE_ID
	 * @return  the value of CRSL_FIELD.CRSL_TABLE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslTableId() {
		return crslTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_TABLE_ID
	 * @param crslTableId  the value for CRSL_FIELD.CRSL_TABLE_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslTableId(Integer crslTableId) {
		this.crslTableId = crslTableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_TEMPLATE
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_TEMPLATE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldTemplate() {
		return crslFieldTemplate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_TEMPLATE
	 * @param crslFieldTemplate  the value for CRSL_FIELD.CRSL_FIELD_TEMPLATE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldTemplate(String crslFieldTemplate) {
		this.crslFieldTemplate = crslFieldTemplate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_DATAFORMATSTRING
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_DATAFORMATSTRING
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldDataformatstring() {
		return crslFieldDataformatstring;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_DATAFORMATSTRING
	 * @param crslFieldDataformatstring  the value for CRSL_FIELD.CRSL_FIELD_DATAFORMATSTRING
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldDataformatstring(String crslFieldDataformatstring) {
		this.crslFieldDataformatstring = crslFieldDataformatstring;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_DATAFIELDTYPE
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_DATAFIELDTYPE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslFieldDatafieldtype() {
		return crslFieldDatafieldtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_DATAFIELDTYPE
	 * @param crslFieldDatafieldtype  the value for CRSL_FIELD.CRSL_FIELD_DATAFIELDTYPE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldDatafieldtype(Integer crslFieldDatafieldtype) {
		this.crslFieldDatafieldtype = crslFieldDatafieldtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_DISPLAYNAME
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_DISPLAYNAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldDisplayname() {
		return crslFieldDisplayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_DISPLAYNAME
	 * @param crslFieldDisplayname  the value for CRSL_FIELD.CRSL_FIELD_DISPLAYNAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldDisplayname(String crslFieldDisplayname) {
		this.crslFieldDisplayname = crslFieldDisplayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_SORTABLE
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_SORTABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Boolean getCrslFieldSortable() {
		return crslFieldSortable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_SORTABLE
	 * @param crslFieldSortable  the value for CRSL_FIELD.CRSL_FIELD_SORTABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldSortable(Boolean crslFieldSortable) {
		this.crslFieldSortable = crslFieldSortable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_TITLE
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_TITLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldTitle() {
		return crslFieldTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_TITLE
	 * @param crslFieldTitle  the value for CRSL_FIELD.CRSL_FIELD_TITLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldTitle(String crslFieldTitle) {
		this.crslFieldTitle = crslFieldTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_HASHISTORYAVAILABLE
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_HASHISTORYAVAILABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Boolean getCrslFieldHashistoryavailable() {
		return crslFieldHashistoryavailable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_HASHISTORYAVAILABLE
	 * @param crslFieldHashistoryavailable  the value for CRSL_FIELD.CRSL_FIELD_HASHISTORYAVAILABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldHashistoryavailable(Boolean crslFieldHashistoryavailable) {
		this.crslFieldHashistoryavailable = crslFieldHashistoryavailable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_SORTORDER
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_SORTORDER
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getCrslFieldSortorder() {
		return crslFieldSortorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_SORTORDER
	 * @param crslFieldSortorder  the value for CRSL_FIELD.CRSL_FIELD_SORTORDER
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldSortorder(Integer crslFieldSortorder) {
		this.crslFieldSortorder = crslFieldSortorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_FIELD
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldAttributesCrslField() {
		return crslFieldAttributesCrslField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_FIELD
	 * @param crslFieldAttributesCrslField  the value for CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldAttributesCrslField(String crslFieldAttributesCrslField) {
		this.crslFieldAttributesCrslField = crslFieldAttributesCrslField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_NG_CLICK
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_NG_CLICK
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldAttributesNgClick() {
		return crslFieldAttributesNgClick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_NG_CLICK
	 * @param crslFieldAttributesNgClick  the value for CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_NG_CLICK
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldAttributesNgClick(String crslFieldAttributesNgClick) {
		this.crslFieldAttributesNgClick = crslFieldAttributesNgClick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_STYLE
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_STYLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldAttributesStyle() {
		return crslFieldAttributesStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_STYLE
	 * @param crslFieldAttributesStyle  the value for CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_STYLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldAttributesStyle(String crslFieldAttributesStyle) {
		this.crslFieldAttributesStyle = crslFieldAttributesStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CLASS
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CLASS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldAttributesClass() {
		return crslFieldAttributesClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CLASS
	 * @param crslFieldAttributesClass  the value for CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CLASS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldAttributesClass(String crslFieldAttributesClass) {
		this.crslFieldAttributesClass = crslFieldAttributesClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_INGRID
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_INGRID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Boolean getCrslFieldAttributesCrslIngrid() {
		return crslFieldAttributesCrslIngrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_INGRID
	 * @param crslFieldAttributesCrslIngrid  the value for CRSL_FIELD.CRSL_FIELD_ATTRIBUTES_CRSL_INGRID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldAttributesCrslIngrid(Boolean crslFieldAttributesCrslIngrid) {
		this.crslFieldAttributesCrslIngrid = crslFieldAttributesCrslIngrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_FIELD
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldHeaderAttributesCrslField() {
		return crslFieldHeaderAttributesCrslField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_FIELD
	 * @param crslFieldHeaderAttributesCrslField  the value for CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldHeaderAttributesCrslField(String crslFieldHeaderAttributesCrslField) {
		this.crslFieldHeaderAttributesCrslField = crslFieldHeaderAttributesCrslField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_NG_CLICK
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_NG_CLICK
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldHeaderAttributesNgClick() {
		return crslFieldHeaderAttributesNgClick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_NG_CLICK
	 * @param crslFieldHeaderAttributesNgClick  the value for CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_NG_CLICK
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldHeaderAttributesNgClick(String crslFieldHeaderAttributesNgClick) {
		this.crslFieldHeaderAttributesNgClick = crslFieldHeaderAttributesNgClick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_STYLE
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_STYLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldHeaderAttributesStyle() {
		return crslFieldHeaderAttributesStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_STYLE
	 * @param crslFieldHeaderAttributesStyle  the value for CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_STYLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldHeaderAttributesStyle(String crslFieldHeaderAttributesStyle) {
		this.crslFieldHeaderAttributesStyle = crslFieldHeaderAttributesStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CLASS
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CLASS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getCrslFieldHeaderAttributesClass() {
		return crslFieldHeaderAttributesClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CLASS
	 * @param crslFieldHeaderAttributesClass  the value for CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CLASS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldHeaderAttributesClass(String crslFieldHeaderAttributesClass) {
		this.crslFieldHeaderAttributesClass = crslFieldHeaderAttributesClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_INGRID
	 * @return  the value of CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_INGRID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Boolean getCrslFieldHeaderAttributesCrslIngrid() {
		return crslFieldHeaderAttributesCrslIngrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_INGRID
	 * @param crslFieldHeaderAttributesCrslIngrid  the value for CRSL_FIELD.CRSL_FIELD_HEADER_ATTRIBUTES_CRSL_INGRID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCrslFieldHeaderAttributesCrslIngrid(Boolean crslFieldHeaderAttributesCrslIngrid) {
		this.crslFieldHeaderAttributesCrslIngrid = crslFieldHeaderAttributesCrslIngrid;
	}
}