package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table QRTZ_FIRED_TRIGGERS
 */
public class QrtzFiredTriggers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String schedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.ENTRY_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String entryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.TRIGGER_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String triggerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String triggerGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.INSTANCE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String instanceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.FIRED_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Long firedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.SCHED_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Long schedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.PRIORITY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.STATE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.JOB_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String jobName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.JOB_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String jobGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.IS_NONCONCURRENT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String isNonconcurrent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String requestsRecovery;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.SCHED_NAME
	 * @return  the value of QRTZ_FIRED_TRIGGERS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSchedName() {
		return schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.SCHED_NAME
	 * @param schedName  the value for QRTZ_FIRED_TRIGGERS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSchedName(String schedName) {
		this.schedName = schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.ENTRY_ID
	 * @return  the value of QRTZ_FIRED_TRIGGERS.ENTRY_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getEntryId() {
		return entryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.ENTRY_ID
	 * @param entryId  the value for QRTZ_FIRED_TRIGGERS.ENTRY_ID
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setEntryId(String entryId) {
		this.entryId = entryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.TRIGGER_NAME
	 * @return  the value of QRTZ_FIRED_TRIGGERS.TRIGGER_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getTriggerName() {
		return triggerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.TRIGGER_NAME
	 * @param triggerName  the value for QRTZ_FIRED_TRIGGERS.TRIGGER_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setTriggerName(String triggerName) {
		this.triggerName = triggerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP
	 * @return  the value of QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getTriggerGroup() {
		return triggerGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP
	 * @param triggerGroup  the value for QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setTriggerGroup(String triggerGroup) {
		this.triggerGroup = triggerGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.INSTANCE_NAME
	 * @return  the value of QRTZ_FIRED_TRIGGERS.INSTANCE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getInstanceName() {
		return instanceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.INSTANCE_NAME
	 * @param instanceName  the value for QRTZ_FIRED_TRIGGERS.INSTANCE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setInstanceName(String instanceName) {
		this.instanceName = instanceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.FIRED_TIME
	 * @return  the value of QRTZ_FIRED_TRIGGERS.FIRED_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Long getFiredTime() {
		return firedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.FIRED_TIME
	 * @param firedTime  the value for QRTZ_FIRED_TRIGGERS.FIRED_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setFiredTime(Long firedTime) {
		this.firedTime = firedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.SCHED_TIME
	 * @return  the value of QRTZ_FIRED_TRIGGERS.SCHED_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Long getSchedTime() {
		return schedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.SCHED_TIME
	 * @param schedTime  the value for QRTZ_FIRED_TRIGGERS.SCHED_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSchedTime(Long schedTime) {
		this.schedTime = schedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.PRIORITY
	 * @return  the value of QRTZ_FIRED_TRIGGERS.PRIORITY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.PRIORITY
	 * @param priority  the value for QRTZ_FIRED_TRIGGERS.PRIORITY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.STATE
	 * @return  the value of QRTZ_FIRED_TRIGGERS.STATE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.STATE
	 * @param state  the value for QRTZ_FIRED_TRIGGERS.STATE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.JOB_NAME
	 * @return  the value of QRTZ_FIRED_TRIGGERS.JOB_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.JOB_NAME
	 * @param jobName  the value for QRTZ_FIRED_TRIGGERS.JOB_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.JOB_GROUP
	 * @return  the value of QRTZ_FIRED_TRIGGERS.JOB_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getJobGroup() {
		return jobGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.JOB_GROUP
	 * @param jobGroup  the value for QRTZ_FIRED_TRIGGERS.JOB_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setJobGroup(String jobGroup) {
		this.jobGroup = jobGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.IS_NONCONCURRENT
	 * @return  the value of QRTZ_FIRED_TRIGGERS.IS_NONCONCURRENT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getIsNonconcurrent() {
		return isNonconcurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.IS_NONCONCURRENT
	 * @param isNonconcurrent  the value for QRTZ_FIRED_TRIGGERS.IS_NONCONCURRENT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setIsNonconcurrent(String isNonconcurrent) {
		this.isNonconcurrent = isNonconcurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY
	 * @return  the value of QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getRequestsRecovery() {
		return requestsRecovery;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY
	 * @param requestsRecovery  the value for QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setRequestsRecovery(String requestsRecovery) {
		this.requestsRecovery = requestsRecovery;
	}
}