package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table QRTZ_SCHEDULER_STATE
 */
public class QrtzSchedulerState {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SCHEDULER_STATE.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String schedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String instanceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Long lastCheckinTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Long checkinInterval;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SCHEDULER_STATE.SCHED_NAME
	 * @return  the value of QRTZ_SCHEDULER_STATE.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSchedName() {
		return schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SCHEDULER_STATE.SCHED_NAME
	 * @param schedName  the value for QRTZ_SCHEDULER_STATE.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSchedName(String schedName) {
		this.schedName = schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
	 * @return  the value of QRTZ_SCHEDULER_STATE.INSTANCE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getInstanceName() {
		return instanceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SCHEDULER_STATE.INSTANCE_NAME
	 * @param instanceName  the value for QRTZ_SCHEDULER_STATE.INSTANCE_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setInstanceName(String instanceName) {
		this.instanceName = instanceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
	 * @return  the value of QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Long getLastCheckinTime() {
		return lastCheckinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
	 * @param lastCheckinTime  the value for QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setLastCheckinTime(Long lastCheckinTime) {
		this.lastCheckinTime = lastCheckinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
	 * @return  the value of QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Long getCheckinInterval() {
		return checkinInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
	 * @param checkinInterval  the value for QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setCheckinInterval(Long checkinInterval) {
		this.checkinInterval = checkinInterval;
	}
}