package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
 */
public class QrtzPausedTriggerGrps {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String schedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String triggerGroup;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
	 * @return  the value of QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSchedName() {
		return schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
	 * @param schedName  the value for QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSchedName(String schedName) {
		this.schedName = schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
	 * @return  the value of QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getTriggerGroup() {
		return triggerGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
	 * @param triggerGroup  the value for QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setTriggerGroup(String triggerGroup) {
		this.triggerGroup = triggerGroup;
	}
}