package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table QRTZ_JOB_DETAILS
 */
public class QrtzJobDetails {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String schedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String jobName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String jobGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.DESCRIPTION
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String jobClassName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.IS_DURABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String isDurable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.IS_NONCONCURRENT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String isNonconcurrent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.IS_UPDATE_DATA
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String isUpdateData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String requestsRecovery;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_DATA
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private byte[] jobData;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.SCHED_NAME
	 * @return  the value of QRTZ_JOB_DETAILS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSchedName() {
		return schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.SCHED_NAME
	 * @param schedName  the value for QRTZ_JOB_DETAILS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSchedName(String schedName) {
		this.schedName = schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_NAME
	 * @return  the value of QRTZ_JOB_DETAILS.JOB_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_NAME
	 * @param jobName  the value for QRTZ_JOB_DETAILS.JOB_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_GROUP
	 * @return  the value of QRTZ_JOB_DETAILS.JOB_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getJobGroup() {
		return jobGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_GROUP
	 * @param jobGroup  the value for QRTZ_JOB_DETAILS.JOB_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setJobGroup(String jobGroup) {
		this.jobGroup = jobGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.DESCRIPTION
	 * @return  the value of QRTZ_JOB_DETAILS.DESCRIPTION
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.DESCRIPTION
	 * @param description  the value for QRTZ_JOB_DETAILS.DESCRIPTION
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
	 * @return  the value of QRTZ_JOB_DETAILS.JOB_CLASS_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getJobClassName() {
		return jobClassName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_CLASS_NAME
	 * @param jobClassName  the value for QRTZ_JOB_DETAILS.JOB_CLASS_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setJobClassName(String jobClassName) {
		this.jobClassName = jobClassName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.IS_DURABLE
	 * @return  the value of QRTZ_JOB_DETAILS.IS_DURABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getIsDurable() {
		return isDurable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.IS_DURABLE
	 * @param isDurable  the value for QRTZ_JOB_DETAILS.IS_DURABLE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setIsDurable(String isDurable) {
		this.isDurable = isDurable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.IS_NONCONCURRENT
	 * @return  the value of QRTZ_JOB_DETAILS.IS_NONCONCURRENT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getIsNonconcurrent() {
		return isNonconcurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.IS_NONCONCURRENT
	 * @param isNonconcurrent  the value for QRTZ_JOB_DETAILS.IS_NONCONCURRENT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setIsNonconcurrent(String isNonconcurrent) {
		this.isNonconcurrent = isNonconcurrent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.IS_UPDATE_DATA
	 * @return  the value of QRTZ_JOB_DETAILS.IS_UPDATE_DATA
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getIsUpdateData() {
		return isUpdateData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.IS_UPDATE_DATA
	 * @param isUpdateData  the value for QRTZ_JOB_DETAILS.IS_UPDATE_DATA
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setIsUpdateData(String isUpdateData) {
		this.isUpdateData = isUpdateData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
	 * @return  the value of QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getRequestsRecovery() {
		return requestsRecovery;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
	 * @param requestsRecovery  the value for QRTZ_JOB_DETAILS.REQUESTS_RECOVERY
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setRequestsRecovery(String requestsRecovery) {
		this.requestsRecovery = requestsRecovery;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_DATA
	 * @return  the value of QRTZ_JOB_DETAILS.JOB_DATA
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public byte[] getJobData() {
		return jobData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_DATA
	 * @param jobData  the value for QRTZ_JOB_DETAILS.JOB_DATA
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setJobData(byte[] jobData) {
		this.jobData = jobData;
	}
}