package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table QRTZ_SIMPLE_TRIGGERS
 */
public class QrtzSimpleTriggers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String schedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String triggerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String triggerGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.REPEAT_COUNT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Long repeatCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.REPEAT_INTERVAL
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Long repeatInterval;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.TIMES_TRIGGERED
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Long timesTriggered;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
	 * @return  the value of QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSchedName() {
		return schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
	 * @param schedName  the value for QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSchedName(String schedName) {
		this.schedName = schedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
	 * @return  the value of QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getTriggerName() {
		return triggerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
	 * @param triggerName  the value for QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setTriggerName(String triggerName) {
		this.triggerName = triggerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
	 * @return  the value of QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getTriggerGroup() {
		return triggerGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
	 * @param triggerGroup  the value for QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setTriggerGroup(String triggerGroup) {
		this.triggerGroup = triggerGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.REPEAT_COUNT
	 * @return  the value of QRTZ_SIMPLE_TRIGGERS.REPEAT_COUNT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Long getRepeatCount() {
		return repeatCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.REPEAT_COUNT
	 * @param repeatCount  the value for QRTZ_SIMPLE_TRIGGERS.REPEAT_COUNT
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setRepeatCount(Long repeatCount) {
		this.repeatCount = repeatCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.REPEAT_INTERVAL
	 * @return  the value of QRTZ_SIMPLE_TRIGGERS.REPEAT_INTERVAL
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Long getRepeatInterval() {
		return repeatInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.REPEAT_INTERVAL
	 * @param repeatInterval  the value for QRTZ_SIMPLE_TRIGGERS.REPEAT_INTERVAL
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setRepeatInterval(Long repeatInterval) {
		this.repeatInterval = repeatInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.TIMES_TRIGGERED
	 * @return  the value of QRTZ_SIMPLE_TRIGGERS.TIMES_TRIGGERED
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Long getTimesTriggered() {
		return timesTriggered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.TIMES_TRIGGERED
	 * @param timesTriggered  the value for QRTZ_SIMPLE_TRIGGERS.TIMES_TRIGGERED
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setTimesTriggered(Long timesTriggered) {
		this.timesTriggered = timesTriggered;
	}
}