package com.csicerc.dss.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table web
 *
 * @mbg.generated do_not_delete_during_merge Thu Jul 12 17:09:12 CST 2018
 */
public class Web {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web.web_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webId;
	/**
	 * Database Column Remarks: web站点名称 This field was generated by MyBatis Generator. This field corresponds to the database column web.web_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String webName;
	/**
	 * Database Column Remarks: web首页URL This field was generated by MyBatis Generator. This field corresponds to the database column web.web_home_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String webHomeUrl;
	/**
	 * Database Column Remarks: web自身状态： 1 不能访问 2 网页改版 3 其他爬取异常，异常细节见web_recently_errors字段内容 This field was generated by MyBatis Generator. This field corresponds to the database column web.web_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webStatus;
	/**
	 * Database Column Remarks: 是否启用爬取 This field was generated by MyBatis Generator. This field corresponds to the database column web.web_enabled
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webEnabled;
	/**
	 * Database Column Remarks: 1: 是搜索引擎 This field was generated by MyBatis Generator. This field corresponds to the database column web.web_is_SE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webIsSe;
	/**
	 * Database Column Remarks: 记录最近网站爬取异常 This field was generated by MyBatis Generator. This field corresponds to the database column web.web_recently_errors
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String webRecentlyErrors;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web.web_id
	 * @return  the value of web.web_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebId() {
		return webId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web.web_id
	 * @param webId  the value for web.web_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebId(Integer webId) {
		this.webId = webId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web.web_name
	 * @return  the value of web.web_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getWebName() {
		return webName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web.web_name
	 * @param webName  the value for web.web_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebName(String webName) {
		this.webName = webName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web.web_home_url
	 * @return  the value of web.web_home_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getWebHomeUrl() {
		return webHomeUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web.web_home_url
	 * @param webHomeUrl  the value for web.web_home_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebHomeUrl(String webHomeUrl) {
		this.webHomeUrl = webHomeUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web.web_status
	 * @return  the value of web.web_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebStatus() {
		return webStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web.web_status
	 * @param webStatus  the value for web.web_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebStatus(Integer webStatus) {
		this.webStatus = webStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web.web_enabled
	 * @return  the value of web.web_enabled
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebEnabled() {
		return webEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web.web_enabled
	 * @param webEnabled  the value for web.web_enabled
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebEnabled(Integer webEnabled) {
		this.webEnabled = webEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web.web_is_SE
	 * @return  the value of web.web_is_SE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebIsSe() {
		return webIsSe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web.web_is_SE
	 * @param webIsSe  the value for web.web_is_SE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebIsSe(Integer webIsSe) {
		this.webIsSe = webIsSe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web.web_recently_errors
	 * @return  the value of web.web_recently_errors
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getWebRecentlyErrors() {
		return webRecentlyErrors;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web.web_recently_errors
	 * @param webRecentlyErrors  the value for web.web_recently_errors
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebRecentlyErrors(String webRecentlyErrors) {
		this.webRecentlyErrors = webRecentlyErrors;
	}
}