package com.csicerc.dss.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table web_crawler_schedule
 *
 * @mbg.generated do_not_delete_during_merge Thu Jul 12 17:09:12 CST 2018
 */
public class WebCrawlerSchedule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.web_crawler_schedule_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webCrawlerScheduleId;
	/**
	 * Database Column Remarks: 网站URL ID This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.web_url_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webUrlId;
	/**
	 * Database Column Remarks: 0 未调度 1 调度中 2 调度停止 3 调度出错 This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.web_crawler_schedule_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webCrawlerScheduleStatus;
	/**
	 * Database Column Remarks: 调度间隔单位为天 This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.web_crawler_schedule_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webCrawlerScheduleInterval;
	/**
	 * Database Column Remarks: 计划抓取条数 This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.planed_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer planedCrawledCount;
	/**
	 * Database Column Remarks: 实际抓取条数 This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.actual_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer actualCrawledCount;
	/**
	 * Database Column Remarks: 出错条数 This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.failed_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer failedCrawledCount;
	/**
	 * Database Column Remarks: 调度起始时间 This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.web_crawler_start_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Date webCrawlerStartDate;
	/**
	 * Database Column Remarks: 结束时间 This field was generated by MyBatis Generator. This field corresponds to the database column web_crawler_schedule.web_crawler_end_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Date webCrawlerEndDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.web_crawler_schedule_id
	 * @return  the value of web_crawler_schedule.web_crawler_schedule_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebCrawlerScheduleId() {
		return webCrawlerScheduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.web_crawler_schedule_id
	 * @param webCrawlerScheduleId  the value for web_crawler_schedule.web_crawler_schedule_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebCrawlerScheduleId(Integer webCrawlerScheduleId) {
		this.webCrawlerScheduleId = webCrawlerScheduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.web_url_id
	 * @return  the value of web_crawler_schedule.web_url_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebUrlId() {
		return webUrlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.web_url_id
	 * @param webUrlId  the value for web_crawler_schedule.web_url_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebUrlId(Integer webUrlId) {
		this.webUrlId = webUrlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.web_crawler_schedule_status
	 * @return  the value of web_crawler_schedule.web_crawler_schedule_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebCrawlerScheduleStatus() {
		return webCrawlerScheduleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.web_crawler_schedule_status
	 * @param webCrawlerScheduleStatus  the value for web_crawler_schedule.web_crawler_schedule_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebCrawlerScheduleStatus(Integer webCrawlerScheduleStatus) {
		this.webCrawlerScheduleStatus = webCrawlerScheduleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.web_crawler_schedule_interval
	 * @return  the value of web_crawler_schedule.web_crawler_schedule_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebCrawlerScheduleInterval() {
		return webCrawlerScheduleInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.web_crawler_schedule_interval
	 * @param webCrawlerScheduleInterval  the value for web_crawler_schedule.web_crawler_schedule_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebCrawlerScheduleInterval(Integer webCrawlerScheduleInterval) {
		this.webCrawlerScheduleInterval = webCrawlerScheduleInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.planed_crawled_count
	 * @return  the value of web_crawler_schedule.planed_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getPlanedCrawledCount() {
		return planedCrawledCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.planed_crawled_count
	 * @param planedCrawledCount  the value for web_crawler_schedule.planed_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setPlanedCrawledCount(Integer planedCrawledCount) {
		this.planedCrawledCount = planedCrawledCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.actual_crawled_count
	 * @return  the value of web_crawler_schedule.actual_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getActualCrawledCount() {
		return actualCrawledCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.actual_crawled_count
	 * @param actualCrawledCount  the value for web_crawler_schedule.actual_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setActualCrawledCount(Integer actualCrawledCount) {
		this.actualCrawledCount = actualCrawledCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.failed_crawled_count
	 * @return  the value of web_crawler_schedule.failed_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getFailedCrawledCount() {
		return failedCrawledCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.failed_crawled_count
	 * @param failedCrawledCount  the value for web_crawler_schedule.failed_crawled_count
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setFailedCrawledCount(Integer failedCrawledCount) {
		this.failedCrawledCount = failedCrawledCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.web_crawler_start_date
	 * @return  the value of web_crawler_schedule.web_crawler_start_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Date getWebCrawlerStartDate() {
		return webCrawlerStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.web_crawler_start_date
	 * @param webCrawlerStartDate  the value for web_crawler_schedule.web_crawler_start_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebCrawlerStartDate(Date webCrawlerStartDate) {
		this.webCrawlerStartDate = webCrawlerStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_crawler_schedule.web_crawler_end_date
	 * @return  the value of web_crawler_schedule.web_crawler_end_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Date getWebCrawlerEndDate() {
		return webCrawlerEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_crawler_schedule.web_crawler_end_date
	 * @param webCrawlerEndDate  the value for web_crawler_schedule.web_crawler_end_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebCrawlerEndDate(Date webCrawlerEndDate) {
		this.webCrawlerEndDate = webCrawlerEndDate;
	}
}