package com.csicerc.dss.domain;

import java.util.ArrayList;
import java.util.List;

public class WebCrawlerScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public WebCrawlerScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWebCrawlerScheduleIdIsNull() {
            addCriterion("web_crawler_schedule_id is null");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdIsNotNull() {
            addCriterion("web_crawler_schedule_id is not null");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_id =", value, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdNotEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_id <>", value, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdGreaterThan(Integer value) {
            addCriterion("web_crawler_schedule_id >", value, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_id >=", value, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdLessThan(Integer value) {
            addCriterion("web_crawler_schedule_id <", value, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdLessThanOrEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_id <=", value, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdIn(List<Integer> values) {
            addCriterion("web_crawler_schedule_id in", values, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdNotIn(List<Integer> values) {
            addCriterion("web_crawler_schedule_id not in", values, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdBetween(Integer value1, Integer value2) {
            addCriterion("web_crawler_schedule_id between", value1, value2, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("web_crawler_schedule_id not between", value1, value2, "webCrawlerScheduleId");
            return (Criteria) this;
        }

        public Criteria andWebIdIsNull() {
            addCriterion("web_id is null");
            return (Criteria) this;
        }

        public Criteria andWebIdIsNotNull() {
            addCriterion("web_id is not null");
            return (Criteria) this;
        }

        public Criteria andWebIdEqualTo(Integer value) {
            addCriterion("web_id =", value, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdNotEqualTo(Integer value) {
            addCriterion("web_id <>", value, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdGreaterThan(Integer value) {
            addCriterion("web_id >", value, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("web_id >=", value, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdLessThan(Integer value) {
            addCriterion("web_id <", value, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdLessThanOrEqualTo(Integer value) {
            addCriterion("web_id <=", value, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdIn(List<Integer> values) {
            addCriterion("web_id in", values, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdNotIn(List<Integer> values) {
            addCriterion("web_id not in", values, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdBetween(Integer value1, Integer value2) {
            addCriterion("web_id between", value1, value2, "webId");
            return (Criteria) this;
        }

        public Criteria andWebIdNotBetween(Integer value1, Integer value2) {
            addCriterion("web_id not between", value1, value2, "webId");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusIsNull() {
            addCriterion("web_crawler_schedule_status is null");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusIsNotNull() {
            addCriterion("web_crawler_schedule_status is not null");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_status =", value, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusNotEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_status <>", value, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusGreaterThan(Integer value) {
            addCriterion("web_crawler_schedule_status >", value, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_status >=", value, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusLessThan(Integer value) {
            addCriterion("web_crawler_schedule_status <", value, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusLessThanOrEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_status <=", value, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusIn(List<Integer> values) {
            addCriterion("web_crawler_schedule_status in", values, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusNotIn(List<Integer> values) {
            addCriterion("web_crawler_schedule_status not in", values, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusBetween(Integer value1, Integer value2) {
            addCriterion("web_crawler_schedule_status between", value1, value2, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("web_crawler_schedule_status not between", value1, value2, "webCrawlerScheduleStatus");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalIsNull() {
            addCriterion("web_crawler_schedule_interval is null");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalIsNotNull() {
            addCriterion("web_crawler_schedule_interval is not null");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_interval =", value, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalNotEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_interval <>", value, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalGreaterThan(Integer value) {
            addCriterion("web_crawler_schedule_interval >", value, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_interval >=", value, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalLessThan(Integer value) {
            addCriterion("web_crawler_schedule_interval <", value, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalLessThanOrEqualTo(Integer value) {
            addCriterion("web_crawler_schedule_interval <=", value, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalIn(List<Integer> values) {
            addCriterion("web_crawler_schedule_interval in", values, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalNotIn(List<Integer> values) {
            addCriterion("web_crawler_schedule_interval not in", values, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalBetween(Integer value1, Integer value2) {
            addCriterion("web_crawler_schedule_interval between", value1, value2, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }

        public Criteria andWebCrawlerScheduleIntervalNotBetween(Integer value1, Integer value2) {
            addCriterion("web_crawler_schedule_interval not between", value1, value2, "webCrawlerScheduleInterval");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 19 10:33:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_crawler_schedule
     *
     * @mbg.generated Thu Jul 19 10:33:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}