package com.csicerc.dss.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table web_url
 */
public class WebUrl {

	/**
	 * Database Column Remarks: 主键，自动生成数字序列 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_url_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webUrlId;
	/**
	 * Database Column Remarks: 网站名字 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_url_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String webUrlName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webId;
	/**
	 * Database Column Remarks: 0 能正常抓取 1 网站页面变化，解析异常 2 网页不存在 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webStatus;
	/**
	 * Database Column Remarks: 查询的url；例：http://www.eworldship.com/app/search?typeid=1&q= This field was generated by MyBatis Generator. This field corresponds to the database column web_url.query_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String queryUrl;
	/**
	 * Database Column Remarks: 翻页中第一页的url，有些网站滴液比较特殊，正常的忽略此字段 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.first_page_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String firstPageUrl;
	/**
	 * Database Column Remarks: 第二页起始页码，和first_page_url配合使用，处理第一页没有页号的场景 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.second_page_num
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer secondPageNum;
	/**
	 * Database Column Remarks: 查询的page参数字符串；例：&p= 全网址为：http://www.eworldship.com/app/search?typeid=1&q='智能'&p=1          即搜索‘智能’的第一页搜索结果。 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.query_page_pattern
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String queryPagePattern;
	/**
	 * Database Column Remarks: JSOUP中使用的解析每个具体文章链接的select tag定义 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.select_tag_article_link
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String selectTagArticleLink;
	/**
	 * Database Column Remarks: JSOUP中使用的解析每个具体文章标题的select tag定义 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.select_tag_article_title
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String selectTagArticleTitle;
	/**
	 * Database Column Remarks: JSOUP中使用的解析每个具体文章发布日期的select tag定义 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.select_tag_article_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String selectTagArticleDate;
	/**
	 * Database Column Remarks: JSOUP中使用的解析每个具体文章内容的select tag定义 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.select_tag_article_content
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String selectTagArticleContent;
	/**
	 * Database Column Remarks: 1 普通网站 2 RestAPI 3 其他特殊类型等 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_url_type
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webUrlType;
	/**
	 * Database Column Remarks: 自定义爬虫类，如果不是普通网站不能统一抓取，要单独为这个网站写一个自定义的抓取类 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_crawler_class
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String webCrawlerClass;
	/**
	 * Database Column Remarks: 下载两个网页间隔毫秒数，防止趴的过快拒绝访问 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_crawler_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webCrawlerInterval;
	/**
	 * Database Column Remarks: 按照客户需求是否抓取 1=抓取 0=不抓取 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_crawler_enable
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webCrawlerEnable;
	/**
	 * Database Column Remarks: 文章发布日期日期标签内容模式 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_date_pattern
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String webDatePattern;
	/**
	 * Database Column Remarks: 文章发布日期日期格式 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_date_format
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String webDateFormat;
	/**
	 * Database Column Remarks: 访问网页的超时时间 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.web_url_timeout
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer webUrlTimeout;
	/**
	 * Database Column Remarks: 只抓取某个时间点后的文章 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.article_date_begin
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Date articleDateBegin;
	/**
	 * Database Column Remarks: 只抓取最近几天，如果设置非零值，优先级高于article_date_begin This field was generated by MyBatis Generator. This field corresponds to the database column web_url.article_date_recently_days
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer articleDateRecentlyDays;
	/**
	 * Database Column Remarks: 备注 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.comments
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String comments;
	/**
	 * Database Column Remarks: 0 多页列表文章 1 只有一页列表 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.single_page
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer singlePage;
	/**
	 * Database Column Remarks: 移除多余的行，这里定义行中关键字，多个关键字分号分割 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.remove_lines_keywords
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private String removeLinesKeywords;
	/**
	 * Database Column Remarks: 移除首部的几个行 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.remove_head_lines
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer removeHeadLines;
	/**
	 * Database Column Remarks: 移除尾部的几个行 This field was generated by MyBatis Generator. This field corresponds to the database column web_url.remove_tail_lines
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	private Integer removeTailLines;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_url_id
	 * @return  the value of web_url.web_url_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebUrlId() {
		return webUrlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_url_id
	 * @param webUrlId  the value for web_url.web_url_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebUrlId(Integer webUrlId) {
		this.webUrlId = webUrlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_url_name
	 * @return  the value of web_url.web_url_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getWebUrlName() {
		return webUrlName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_url_name
	 * @param webUrlName  the value for web_url.web_url_name
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebUrlName(String webUrlName) {
		this.webUrlName = webUrlName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_id
	 * @return  the value of web_url.web_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebId() {
		return webId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_id
	 * @param webId  the value for web_url.web_id
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebId(Integer webId) {
		this.webId = webId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_status
	 * @return  the value of web_url.web_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebStatus() {
		return webStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_status
	 * @param webStatus  the value for web_url.web_status
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebStatus(Integer webStatus) {
		this.webStatus = webStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.query_url
	 * @return  the value of web_url.query_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getQueryUrl() {
		return queryUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.query_url
	 * @param queryUrl  the value for web_url.query_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setQueryUrl(String queryUrl) {
		this.queryUrl = queryUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.first_page_url
	 * @return  the value of web_url.first_page_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getFirstPageUrl() {
		return firstPageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.first_page_url
	 * @param firstPageUrl  the value for web_url.first_page_url
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setFirstPageUrl(String firstPageUrl) {
		this.firstPageUrl = firstPageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.second_page_num
	 * @return  the value of web_url.second_page_num
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getSecondPageNum() {
		return secondPageNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.second_page_num
	 * @param secondPageNum  the value for web_url.second_page_num
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSecondPageNum(Integer secondPageNum) {
		this.secondPageNum = secondPageNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.query_page_pattern
	 * @return  the value of web_url.query_page_pattern
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getQueryPagePattern() {
		return queryPagePattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.query_page_pattern
	 * @param queryPagePattern  the value for web_url.query_page_pattern
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setQueryPagePattern(String queryPagePattern) {
		this.queryPagePattern = queryPagePattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.select_tag_article_link
	 * @return  the value of web_url.select_tag_article_link
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSelectTagArticleLink() {
		return selectTagArticleLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.select_tag_article_link
	 * @param selectTagArticleLink  the value for web_url.select_tag_article_link
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSelectTagArticleLink(String selectTagArticleLink) {
		this.selectTagArticleLink = selectTagArticleLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.select_tag_article_title
	 * @return  the value of web_url.select_tag_article_title
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSelectTagArticleTitle() {
		return selectTagArticleTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.select_tag_article_title
	 * @param selectTagArticleTitle  the value for web_url.select_tag_article_title
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSelectTagArticleTitle(String selectTagArticleTitle) {
		this.selectTagArticleTitle = selectTagArticleTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.select_tag_article_date
	 * @return  the value of web_url.select_tag_article_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSelectTagArticleDate() {
		return selectTagArticleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.select_tag_article_date
	 * @param selectTagArticleDate  the value for web_url.select_tag_article_date
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSelectTagArticleDate(String selectTagArticleDate) {
		this.selectTagArticleDate = selectTagArticleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.select_tag_article_content
	 * @return  the value of web_url.select_tag_article_content
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getSelectTagArticleContent() {
		return selectTagArticleContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.select_tag_article_content
	 * @param selectTagArticleContent  the value for web_url.select_tag_article_content
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSelectTagArticleContent(String selectTagArticleContent) {
		this.selectTagArticleContent = selectTagArticleContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_url_type
	 * @return  the value of web_url.web_url_type
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebUrlType() {
		return webUrlType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_url_type
	 * @param webUrlType  the value for web_url.web_url_type
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebUrlType(Integer webUrlType) {
		this.webUrlType = webUrlType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_crawler_class
	 * @return  the value of web_url.web_crawler_class
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getWebCrawlerClass() {
		return webCrawlerClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_crawler_class
	 * @param webCrawlerClass  the value for web_url.web_crawler_class
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebCrawlerClass(String webCrawlerClass) {
		this.webCrawlerClass = webCrawlerClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_crawler_interval
	 * @return  the value of web_url.web_crawler_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebCrawlerInterval() {
		return webCrawlerInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_crawler_interval
	 * @param webCrawlerInterval  the value for web_url.web_crawler_interval
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebCrawlerInterval(Integer webCrawlerInterval) {
		this.webCrawlerInterval = webCrawlerInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_crawler_enable
	 * @return  the value of web_url.web_crawler_enable
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebCrawlerEnable() {
		return webCrawlerEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_crawler_enable
	 * @param webCrawlerEnable  the value for web_url.web_crawler_enable
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebCrawlerEnable(Integer webCrawlerEnable) {
		this.webCrawlerEnable = webCrawlerEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_date_pattern
	 * @return  the value of web_url.web_date_pattern
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getWebDatePattern() {
		return webDatePattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_date_pattern
	 * @param webDatePattern  the value for web_url.web_date_pattern
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebDatePattern(String webDatePattern) {
		this.webDatePattern = webDatePattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_date_format
	 * @return  the value of web_url.web_date_format
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getWebDateFormat() {
		return webDateFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_date_format
	 * @param webDateFormat  the value for web_url.web_date_format
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebDateFormat(String webDateFormat) {
		this.webDateFormat = webDateFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.web_url_timeout
	 * @return  the value of web_url.web_url_timeout
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getWebUrlTimeout() {
		return webUrlTimeout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.web_url_timeout
	 * @param webUrlTimeout  the value for web_url.web_url_timeout
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setWebUrlTimeout(Integer webUrlTimeout) {
		this.webUrlTimeout = webUrlTimeout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.article_date_begin
	 * @return  the value of web_url.article_date_begin
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Date getArticleDateBegin() {
		return articleDateBegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.article_date_begin
	 * @param articleDateBegin  the value for web_url.article_date_begin
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setArticleDateBegin(Date articleDateBegin) {
		this.articleDateBegin = articleDateBegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.article_date_recently_days
	 * @return  the value of web_url.article_date_recently_days
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getArticleDateRecentlyDays() {
		return articleDateRecentlyDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.article_date_recently_days
	 * @param articleDateRecentlyDays  the value for web_url.article_date_recently_days
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setArticleDateRecentlyDays(Integer articleDateRecentlyDays) {
		this.articleDateRecentlyDays = articleDateRecentlyDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.comments
	 * @return  the value of web_url.comments
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.comments
	 * @param comments  the value for web_url.comments
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.single_page
	 * @return  the value of web_url.single_page
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getSinglePage() {
		return singlePage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.single_page
	 * @param singlePage  the value for web_url.single_page
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setSinglePage(Integer singlePage) {
		this.singlePage = singlePage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.remove_lines_keywords
	 * @return  the value of web_url.remove_lines_keywords
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public String getRemoveLinesKeywords() {
		return removeLinesKeywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.remove_lines_keywords
	 * @param removeLinesKeywords  the value for web_url.remove_lines_keywords
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setRemoveLinesKeywords(String removeLinesKeywords) {
		this.removeLinesKeywords = removeLinesKeywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.remove_head_lines
	 * @return  the value of web_url.remove_head_lines
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getRemoveHeadLines() {
		return removeHeadLines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.remove_head_lines
	 * @param removeHeadLines  the value for web_url.remove_head_lines
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setRemoveHeadLines(Integer removeHeadLines) {
		this.removeHeadLines = removeHeadLines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column web_url.remove_tail_lines
	 * @return  the value of web_url.remove_tail_lines
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public Integer getRemoveTailLines() {
		return removeTailLines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column web_url.remove_tail_lines
	 * @param removeTailLines  the value for web_url.remove_tail_lines
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	public void setRemoveTailLines(Integer removeTailLines) {
		this.removeTailLines = removeTailLines;
	}
}