package com.csicerc.dss.service.aaa;

public class DataDictionaryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.DataCode
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    private String datacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.DataType
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    private String datatype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.DataCode
     *
     * @return the value of data_dictionary.DataCode
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    public String getDatacode() {
        return datacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.DataCode
     *
     * @param datacode the value for data_dictionary.DataCode
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    public void setDatacode(String datacode) {
        this.datacode = datacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.DataType
     *
     * @return the value of data_dictionary.DataType
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.DataType
     *
     * @param datatype the value for data_dictionary.DataType
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }
}