package com.csicerc.dss.service.aaa;

public class DataDictionary extends DataDictionaryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.DataValue
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    private String datavalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.DataValue
     *
     * @return the value of data_dictionary.DataValue
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    public String getDatavalue() {
        return datavalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.DataValue
     *
     * @param datavalue the value for data_dictionary.DataValue
     *
     * @mbg.generated Sun Aug 13 10:19:49 CST 2017
     */
    public void setDatavalue(String datavalue) {
        this.datavalue = datavalue;
    }
}