package com.csicerc.dss.service.aaa;

import java.util.Date;

public class RoleUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_user.RoleUserCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	private String roleusercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_user.RoleCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	private String rolecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_user.UserCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	private String usercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_user.CreateUser
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_user.CreateDate
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_user.Status
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_user.RoleUserCode
	 * @return  the value of role_user.RoleUserCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public String getRoleusercode() {
		return roleusercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_user.RoleUserCode
	 * @param roleusercode  the value for role_user.RoleUserCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public void setRoleusercode(String roleusercode) {
		this.roleusercode = roleusercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_user.RoleCode
	 * @return  the value of role_user.RoleCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public String getRolecode() {
		return rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_user.RoleCode
	 * @param rolecode  the value for role_user.RoleCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public void setRolecode(String rolecode) {
		this.rolecode = rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_user.UserCode
	 * @return  the value of role_user.UserCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public String getUsercode() {
		return usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_user.UserCode
	 * @param usercode  the value for role_user.UserCode
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_user.CreateUser
	 * @return  the value of role_user.CreateUser
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_user.CreateUser
	 * @param createuser  the value for role_user.CreateUser
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_user.CreateDate
	 * @return  the value of role_user.CreateDate
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_user.CreateDate
	 * @param createdate  the value for role_user.CreateDate
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_user.Status
	 * @return  the value of role_user.Status
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_user.Status
	 * @param status  the value for role_user.Status
	 * @mbg.generated  Tue Aug 08 15:51:30 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}