package com.csicerc.dss.service.aaa;

import java.util.Date;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.RoleCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	private String rolecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.TenantCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	private String tenantcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.DeptCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	private String deptcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.Name
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.CreateUser
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.CreateDate
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.Status
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.RoleCode
	 * @return  the value of role.RoleCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public String getRolecode() {
		return rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.RoleCode
	 * @param rolecode  the value for role.RoleCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public void setRolecode(String rolecode) {
		this.rolecode = rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.TenantCode
	 * @return  the value of role.TenantCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public String getTenantcode() {
		return tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.TenantCode
	 * @param tenantcode  the value for role.TenantCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public void setTenantcode(String tenantcode) {
		this.tenantcode = tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.DeptCode
	 * @return  the value of role.DeptCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public String getDeptcode() {
		return deptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.DeptCode
	 * @param deptcode  the value for role.DeptCode
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.Name
	 * @return  the value of role.Name
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.Name
	 * @param name  the value for role.Name
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.CreateUser
	 * @return  the value of role.CreateUser
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.CreateUser
	 * @param createuser  the value for role.CreateUser
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.CreateDate
	 * @return  the value of role.CreateDate
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.CreateDate
	 * @param createdate  the value for role.CreateDate
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.Status
	 * @return  the value of role.Status
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.Status
	 * @param status  the value for role.Status
	 * @mbg.generated  Tue Aug 08 15:53:53 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}