package com.csicerc.dss.service.aaa;

import java.util.Date;

public class SysDepts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_depts.DeptCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String deptcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_depts.EnterpriseCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String enterprisecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_depts.DeptName
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String deptname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_depts.DeptAddre
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String deptaddre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_depts.Dept_OrganizeDate
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private Date deptOrganizedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_depts.Telphone
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_depts.MailAddress
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String mailaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_depts.LinkManCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String linkmancode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_depts.DeptCode
	 * @return  the value of sys_depts.DeptCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getDeptcode() {
		return deptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_depts.DeptCode
	 * @param deptcode  the value for sys_depts.DeptCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_depts.EnterpriseCode
	 * @return  the value of sys_depts.EnterpriseCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getEnterprisecode() {
		return enterprisecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_depts.EnterpriseCode
	 * @param enterprisecode  the value for sys_depts.EnterpriseCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_depts.DeptName
	 * @return  the value of sys_depts.DeptName
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getDeptname() {
		return deptname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_depts.DeptName
	 * @param deptname  the value for sys_depts.DeptName
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_depts.DeptAddre
	 * @return  the value of sys_depts.DeptAddre
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getDeptaddre() {
		return deptaddre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_depts.DeptAddre
	 * @param deptaddre  the value for sys_depts.DeptAddre
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setDeptaddre(String deptaddre) {
		this.deptaddre = deptaddre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_depts.Dept_OrganizeDate
	 * @return  the value of sys_depts.Dept_OrganizeDate
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public Date getDeptOrganizedate() {
		return deptOrganizedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_depts.Dept_OrganizeDate
	 * @param deptOrganizedate  the value for sys_depts.Dept_OrganizeDate
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setDeptOrganizedate(Date deptOrganizedate) {
		this.deptOrganizedate = deptOrganizedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_depts.Telphone
	 * @return  the value of sys_depts.Telphone
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_depts.Telphone
	 * @param telephone  the value for sys_depts.Telphone
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_depts.MailAddress
	 * @return  the value of sys_depts.MailAddress
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getMailaddress() {
		return mailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_depts.MailAddress
	 * @param mailaddress  the value for sys_depts.MailAddress
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setMailaddress(String mailaddress) {
		this.mailaddress = mailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_depts.LinkManCode
	 * @return  the value of sys_depts.LinkManCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getLinkmancode() {
		return linkmancode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_depts.LinkManCode
	 * @param linkmancode  the value for sys_depts.LinkManCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setLinkmancode(String linkmancode) {
		this.linkmancode = linkmancode;
	}
}