package com.csicerc.dss.service.aaa;

import java.util.Date;

public class SysRolesResources {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_roles_resources.RoleResourceCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	private String roleresourcecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_roles_resources.RoleCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	private String rolecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_roles_resources.CreateUser
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_roles_resources.CreateDate
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_roles_resources.Status
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_roles_resources.ResourceCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	private String resourceCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_roles_resources.RoleResourceCode
	 * @return  the value of sys_roles_resources.RoleResourceCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public String getRoleresourcecode() {
		return roleresourcecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_roles_resources.RoleResourceCode
	 * @param roleresourcecode  the value for sys_roles_resources.RoleResourceCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public void setRoleresourcecode(String roleresourcecode) {
		this.roleresourcecode = roleresourcecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_roles_resources.RoleCode
	 * @return  the value of sys_roles_resources.RoleCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public String getRolecode() {
		return rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_roles_resources.RoleCode
	 * @param rolecode  the value for sys_roles_resources.RoleCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public void setRolecode(String rolecode) {
		this.rolecode = rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_roles_resources.CreateUser
	 * @return  the value of sys_roles_resources.CreateUser
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_roles_resources.CreateUser
	 * @param createuser  the value for sys_roles_resources.CreateUser
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_roles_resources.CreateDate
	 * @return  the value of sys_roles_resources.CreateDate
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_roles_resources.CreateDate
	 * @param createdate  the value for sys_roles_resources.CreateDate
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_roles_resources.Status
	 * @return  the value of sys_roles_resources.Status
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_roles_resources.Status
	 * @param status  the value for sys_roles_resources.Status
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_roles_resources.ResourceCode
	 * @return  the value of sys_roles_resources.ResourceCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public String getResourceCode() {
		return resourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_roles_resources.ResourceCode
	 * @param resourceCode  the value for sys_roles_resources.ResourceCode
	 * @mbg.generated  Tue Aug 08 15:28:57 CST 2017
	 */
	public void setResourceCode(String resourceCode) {
		this.resourceCode = resourceCode;
	}
}