package com.csicerc.dss.service.aaa;

public class SysResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.ResourceCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String resourcecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.ParentResourceCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String parentresourcecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.ResourceName
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String resourcename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.ResourceType
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String resourcetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.ResourceUrl
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private String resourceurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.IsMune
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private Integer ismune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.IsDir
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private Integer isdir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.Status
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.ResourceCode
	 * @return  the value of sys_resource.ResourceCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getResourcecode() {
		return resourcecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.ResourceCode
	 * @param resourcecode  the value for sys_resource.ResourceCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setResourcecode(String resourcecode) {
		this.resourcecode = resourcecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.ParentResourceCode
	 * @return  the value of sys_resource.ParentResourceCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getParentresourcecode() {
		return parentresourcecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.ParentResourceCode
	 * @param parentresourcecode  the value for sys_resource.ParentResourceCode
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setParentresourcecode(String parentresourcecode) {
		this.parentresourcecode = parentresourcecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.ResourceName
	 * @return  the value of sys_resource.ResourceName
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getResourcename() {
		return resourcename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.ResourceName
	 * @param resourcename  the value for sys_resource.ResourceName
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setResourcename(String resourcename) {
		this.resourcename = resourcename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.ResourceType
	 * @return  the value of sys_resource.ResourceType
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getResourcetype() {
		return resourcetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.ResourceType
	 * @param resourcetype  the value for sys_resource.ResourceType
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setResourcetype(String resourcetype) {
		this.resourcetype = resourcetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.ResourceUrl
	 * @return  the value of sys_resource.ResourceUrl
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public String getResourceurl() {
		return resourceurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.ResourceUrl
	 * @param resourceurl  the value for sys_resource.ResourceUrl
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setResourceurl(String resourceurl) {
		this.resourceurl = resourceurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.IsMune
	 * @return  the value of sys_resource.IsMune
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public Integer getIsmune() {
		return ismune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.IsMune
	 * @param ismune  the value for sys_resource.IsMune
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setIsmune(Integer ismune) {
		this.ismune = ismune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.IsDir
	 * @return  the value of sys_resource.IsDir
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public Integer getIsdir() {
		return isdir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.IsDir
	 * @param isdir  the value for sys_resource.IsDir
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setIsdir(Integer isdir) {
		this.isdir = isdir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.Status
	 * @return  the value of sys_resource.Status
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.Status
	 * @param status  the value for sys_resource.Status
	 * @mbg.generated  Sun May 14 14:43:19 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}