package com.csicerc.dss.service.aaa;

import java.util.Date;

public class SysUsers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.UserCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String usercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.UserName
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.UserPassword
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String userpassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.Encryption
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String encryption;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.CreateUser
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.CreateDate
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.Status
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.DeptCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String deptcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.TenantCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String tenantcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.PositionCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String positioncode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.Alias
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.LastLoginTime
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private Date lastlogintime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.LoginNumber
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private Integer loginnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.Description
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.Telephone
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_users.Email
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	private String email;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.UserCode
	 * @return  the value of sys_users.UserCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getUsercode() {
		return usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.UserCode
	 * @param usercode  the value for sys_users.UserCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.UserName
	 * @return  the value of sys_users.UserName
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.UserName
	 * @param username  the value for sys_users.UserName
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.UserPassword
	 * @return  the value of sys_users.UserPassword
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getUserpassword() {
		return userpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.UserPassword
	 * @param userpassword  the value for sys_users.UserPassword
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.Encryption
	 * @return  the value of sys_users.Encryption
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getEncryption() {
		return encryption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.Encryption
	 * @param encryption  the value for sys_users.Encryption
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setEncryption(String encryption) {
		this.encryption = encryption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.CreateUser
	 * @return  the value of sys_users.CreateUser
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.CreateUser
	 * @param createuser  the value for sys_users.CreateUser
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.CreateDate
	 * @return  the value of sys_users.CreateDate
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.CreateDate
	 * @param createdate  the value for sys_users.CreateDate
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.Status
	 * @return  the value of sys_users.Status
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.Status
	 * @param status  the value for sys_users.Status
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.DeptCode
	 * @return  the value of sys_users.DeptCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getDeptcode() {
		return deptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.DeptCode
	 * @param deptcode  the value for sys_users.DeptCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.TenantCode
	 * @return  the value of sys_users.TenantCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getTenantcode() {
		return tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.TenantCode
	 * @param tenantcode  the value for sys_users.TenantCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setTenantcode(String tenantcode) {
		this.tenantcode = tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.PositionCode
	 * @return  the value of sys_users.PositionCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getPositioncode() {
		return positioncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.PositionCode
	 * @param positioncode  the value for sys_users.PositionCode
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setPositioncode(String positioncode) {
		this.positioncode = positioncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.Alias
	 * @return  the value of sys_users.Alias
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.Alias
	 * @param alias  the value for sys_users.Alias
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.LastLoginTime
	 * @return  the value of sys_users.LastLoginTime
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public Date getLastlogintime() {
		return lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.LastLoginTime
	 * @param lastlogintime  the value for sys_users.LastLoginTime
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setLastlogintime(Date lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.LoginNumber
	 * @return  the value of sys_users.LoginNumber
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public Integer getLoginnumber() {
		return loginnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.LoginNumber
	 * @param loginnumber  the value for sys_users.LoginNumber
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setLoginnumber(Integer loginnumber) {
		this.loginnumber = loginnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.Description
	 * @return  the value of sys_users.Description
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.Description
	 * @param description  the value for sys_users.Description
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.Telephone
	 * @return  the value of sys_users.Telephone
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.Telephone
	 * @param telephone  the value for sys_users.Telephone
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_users.Email
	 * @return  the value of sys_users.Email
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_users.Email
	 * @param email  the value for sys_users.Email
	 * @mbg.generated  Thu Jan 11 15:21:23 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}