package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.ArticleCategory;
import com.csicerc.dss.domain.ArticleCategoryExample;
import java.util.List;

public interface ArticleCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer articleCategoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(ArticleCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	ArticleCategory selectByPrimaryKey(Integer articleCategoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<ArticleCategory> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(ArticleCategory record);
}