package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.ArticleCategoryKeyword;
import com.csicerc.dss.domain.ArticleCategoryKeywordExample;
import java.util.List;

public interface ArticleCategoryKeywordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category_keyword
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer articleCategoryKeywordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category_keyword
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(ArticleCategoryKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category_keyword
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	ArticleCategoryKeyword selectByPrimaryKey(Integer articleCategoryKeywordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category_keyword
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<ArticleCategoryKeyword> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article_category_keyword
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(ArticleCategoryKeyword record);
}