package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.ClarksonsDownloadSchedule;
import java.util.List;

public interface ClarksonsDownloadScheduleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_download_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer clarksonsDownloadScheduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_download_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(ClarksonsDownloadSchedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_download_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	ClarksonsDownloadSchedule selectByPrimaryKey(Integer clarksonsDownloadScheduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_download_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<ClarksonsDownloadSchedule> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_download_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(ClarksonsDownloadSchedule record);
}