package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.ClarksonsFleet;
import java.util.List;

public interface ClarksonsFleetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_fleet
	 * @mbg.generated  Tue Jul 31 12:43:41 CST 2018
	 */
	int insert(ClarksonsFleet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_fleet
	 * @mbg.generated  Tue Jul 31 12:43:41 CST 2018
	 */
	List<ClarksonsFleet> selectAll();
}