package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.ClarksonsTable;
import java.util.List;

public interface ClarksonsTableMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_table
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer clarksonsTableId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_table
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(ClarksonsTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_table
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	ClarksonsTable selectByPrimaryKey(Integer clarksonsTableId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_table
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<ClarksonsTable> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table clarksons_table
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(ClarksonsTable record);
}