package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.CrslDatabase;
import com.csicerc.dss.domain.CrslDatabaseExample;
import java.util.List;

public interface CrslDatabaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_DATABASE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer crslDatabaseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_DATABASE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(CrslDatabase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_DATABASE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	CrslDatabase selectByPrimaryKey(Integer crslDatabaseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_DATABASE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<CrslDatabase> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_DATABASE
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(CrslDatabase record);
}