package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.CrslTableDownSch;
import com.csicerc.dss.domain.CrslTableDownSchExample;
import java.util.List;

public interface CrslTableDownSchMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_sch
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer crslTableDownSchId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_sch
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(CrslTableDownSch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_sch
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	CrslTableDownSch selectByPrimaryKey(Integer crslTableDownSchId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_sch
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<CrslTableDownSch> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_sch
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(CrslTableDownSch record);
}