package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.CrslTableDownRec;
import com.csicerc.dss.domain.CrslTableDownRecExample;
import java.util.List;

public interface CrslTableDownRecMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_rec
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer crslTableDownRecId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_rec
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(CrslTableDownRec record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_rec
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	CrslTableDownRec selectByPrimaryKey(Integer crslTableDownRecId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_rec
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<CrslTableDownRec> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crsl_table_down_rec
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(CrslTableDownRec record);
}