package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.CrslFields;
import com.csicerc.dss.domain.CrslFieldsExample;
import java.util.List;

public interface CrslFieldsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELDS
	 * @mbg.generated  Tue Jul 31 11:25:01 CST 2018
	 */
	int deleteByPrimaryKey(Integer crslFieldId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELDS
	 * @mbg.generated  Tue Jul 31 11:25:01 CST 2018
	 */
	int insert(CrslFields record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELDS
	 * @mbg.generated  Tue Jul 31 11:25:01 CST 2018
	 */
	CrslFields selectByPrimaryKey(Integer crslFieldId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELDS
	 * @mbg.generated  Tue Jul 31 11:25:01 CST 2018
	 */
	List<CrslFields> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELDS
	 * @mbg.generated  Tue Jul 31 11:25:01 CST 2018
	 */
	int updateByPrimaryKey(CrslFields record);
}