package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.CrslField;
import java.util.List;

public interface CrslFieldMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer crslFieldId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(CrslField record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	CrslField selectByPrimaryKey(Integer crslFieldId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<CrslField> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CRSL_FIELD
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(CrslField record);
}