package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.QrtzSimpropTriggers;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzSimpropTriggersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName,
			@Param("triggerGroup") String triggerGroup);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(QrtzSimpropTriggers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	QrtzSimpropTriggers selectByPrimaryKey(@Param("schedName") String schedName,
			@Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<QrtzSimpropTriggers> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(QrtzSimpropTriggers record);
}