package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.QrtzSimpleTriggers;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzSimpleTriggersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName,
			@Param("triggerGroup") String triggerGroup);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(QrtzSimpleTriggers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	QrtzSimpleTriggers selectByPrimaryKey(@Param("schedName") String schedName,
			@Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<QrtzSimpleTriggers> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(QrtzSimpleTriggers record);
}