package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.QrtzFiredTriggers;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzFiredTriggersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_FIRED_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("entryId") String entryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_FIRED_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(QrtzFiredTriggers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_FIRED_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	QrtzFiredTriggers selectByPrimaryKey(@Param("schedName") String schedName, @Param("entryId") String entryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_FIRED_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<QrtzFiredTriggers> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_FIRED_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(QrtzFiredTriggers record);
}