package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.QrtzCalendars;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzCalendarsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CALENDARS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("calendarName") String calendarName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CALENDARS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(QrtzCalendars record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CALENDARS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	QrtzCalendars selectByPrimaryKey(@Param("schedName") String schedName, @Param("calendarName") String calendarName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CALENDARS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<QrtzCalendars> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CALENDARS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(QrtzCalendars record);
}