package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.QrtzCronTriggers;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzCronTriggersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CRON_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName,
			@Param("triggerGroup") String triggerGroup);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CRON_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(QrtzCronTriggers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CRON_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	QrtzCronTriggers selectByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName,
			@Param("triggerGroup") String triggerGroup);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CRON_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<QrtzCronTriggers> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table QRTZ_CRON_TRIGGERS
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(QrtzCronTriggers record);
}