package com.csicerc.dss.persist.dao;

import com.csicerc.dss.domain.WebCrawlerSchedule;
import com.csicerc.dss.domain.WebCrawlerScheduleExample;
import java.util.List;

public interface WebCrawlerScheduleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_crawler_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int deleteByPrimaryKey(Integer webCrawlerScheduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_crawler_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int insert(WebCrawlerSchedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_crawler_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	WebCrawlerSchedule selectByPrimaryKey(Integer webCrawlerScheduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_crawler_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	List<WebCrawlerSchedule> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table web_crawler_schedule
	 * @mbg.generated  Tue Jul 31 17:28:09 CST 2018
	 */
	int updateByPrimaryKey(WebCrawlerSchedule record);
}